#!/usr/bin/env python 

from subprocess import run
import glob
import os
import fnmatch
import sys

if len(sys.argv) < 2:
    dir = "."
else:
    dir = sys.argv[1]

for midi_file in glob.iglob(dir+"/**", recursive=True):
    if os.path.isfile(midi_file) and fnmatch.fnmatch(midi_file, "*.abc"):
        abc_file = midi_file[:-3] + "mid"
        run(["abc2midi", midi_file, "-o", abc_file])
