#!/bin/bash

# This script splits a sample into songs

# check for arg
if test "$#" -ne 1; then
    echo "Usage: " $0 "sample_file"
    exit
fi

dir=`dirname $1`

# turn \n into newlines and \\ into \
sed -i 's/\\n/\n/g' $1
sed -i 's/\\\\/\\/g' $1

# Split into files
csplit $1 '/^X:/' '{*}';
mv xx* $dir

# rename files
find $dir -type f  ! -name "*.*" -exec mv {} {}.abc \;

# run batch_abc2midi

# done
